version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: challenge_2_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: challenge_2
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  server:
    build: ./server
    container_name: challenge_2_server
    ports:
      - "3001:3001"
    depends_on:
      - db
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    command: >
      sh -lc "npx prisma generate && npx prisma migrate dev --name init && npm run dev"

volumes:
  pgdata:
